// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gtfs_api.Data;

#nullable disable

namespace gtfs_api.Migrations
{
    [DbContext(typeof(GTFSDbContext))]
    [Migration("20240707023528_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("gtfs_api.Data.Route", b =>
                {
                    b.Property<int>("route_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("agency_id")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("route_color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("route_desc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("route_long_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("route_short_name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("route_text_color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("route_type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("route_url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("route_id");

                    b.ToTable("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
